fix: ignore `test.test_wrapper` when runing all in CI even if single is passed

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -29,4 +29,11 @@ jobs:
         python -m unittest test/test_wrapper.py -v
     - name: Test [all]
       run: |
-        python -m unittest -v
+        python -m unittest -v |& tee log.txt
+        grep '^FAIL:' log.txt > fails.txt
+        # if all failures is not raised in `test.test_wrapper`:
+        if [ "$(grep 'test.test_wrapper' fails.txt | wc -l)" -ne "$(wc -l < fails.txt)" ]; then
+          exit 1
+        else
+          echo 'All of the above failures are maybe false error. See: #192'
+        fi
